name: flutter_app2
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.4
  rxdart: 0.22.1
  intl: ^0.16.1
  json_annotation: ^2.0.0
  apple_sign_in: ^0.1.0
  http: ^0.12.0+2
  firebase_database: ^3.1.3
  firebase_core: ^0.4.4+3
  firebase_analytics: ^1.0.4
  firebase_auth: ^0.15.5+3
  flutter_signin_button: ^1.0.0
  flutter_picker: ^1.1.0
  flutter_cupertino_data_picker: ^0.8.6
  charts_flutter: ^0.8.1
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0
  google_sign_in: ^3.0.4
  flutter_spinkit: ^2.1.0
  shared_preferences: ^0.5.6+2
  table_calendar: ^2.2.3
  fl_chart: ^0.8.3
  gradient_app_bar: ^0.1.3
  gradient_bottom_navigation_bar: ^1.0.0+4
  percent_indicator: ^2.1.1+1
  awesome_dialog: ^0.1.3
  solid_bottom_sheet: ^0.1.9





dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/piece/
    - assets/PrivacyPolicy.txt
    - assets/TermsOfService.txt
    - assets/MahjongHandfromWiki.json